"""The persona is a generated file, so a persona bugfix reaches old captains.

A two-arm benchmark measured three losses that all had correct retrieval and a
damaged answer around it: an invented `evt-<today>-...` citation, a headline that
contradicted the literal recorded status, and an uncitable supporting path. The
rules against those (PRINCIPLES_MD 6-8) only help if they arrive, and the old
`ensure_claude_md` inlined the prose and then returned early forever once the
include line existed, so an already-scaffolded captain could never receive one.

Now `.tsubasa/persona.md` is generated and included, exactly like memory/hot.md:
`upgrade` rewrites it, CLAUDE.md is only ever appended to, and the rules live in
one place. These tests pin all three of those properties.
"""

import json
import subprocess
from pathlib import Path

import pytest

from tsubasa import cli, scaffold
from tsubasa.scaffold import PERSONA_FILE, PRINCIPLES_MD

ROOT = Path(__file__).resolve().parent.parent
HOOK = ROOT / "plugin" / "hooks" / "session_start.sh"
RECALL = ROOT / "plugin" / "skills" / "recall" / "SKILL.md"

# One phrase per new rule: the clause carrying the prohibition.
RULES = [
    "**Never cite an id you did not read.**",          # fabricated provenance
    "verbatim in a `tsubasa query` result this session",
    "`evt-<today>-...`",                               # the tell
    "**Lead with the recorded value**",                # literal answer first
    "the successor is never the headline",
    "**Separate the record from what you know.**",
    "not recorded here, from general knowledge",
]


def hook_out(cwd, source="startup"):
    return subprocess.run(
        ["sh", str(HOOK)], cwd=cwd, capture_output=True, text=True,
        input=json.dumps({"hook_event_name": "SessionStart", "source": source}),
    ).stdout


@pytest.fixture()
def fresh(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert cli.main(["init", "testcap"]) == 0
    return tmp_path


# --- the three rules against the measured failures ---

@pytest.mark.parametrize("rule", RULES)
def test_persona_file_carries_every_rule(fresh, rule):
    assert rule in (fresh / ".tsubasa" / PERSONA_FILE).read_text()


def test_numbering_stays_sequential():
    # the three rules were inserted mid-list; a renumbering slip is silent
    import re
    nums = [int(n) for n in re.findall(r"^(\d+)\. \*\*", PRINCIPLES_MD, re.M)]
    assert nums == list(range(1, len(nums) + 1))


def test_persona_stays_injectable():
    # loaded on every session, so wording earns its tokens
    assert len(PRINCIPLES_MD) < 5000
    # practise rule 16: the only em dash allowed here is the one it quotes
    assert PRINCIPLES_MD.count("—") == 1


# --- delivery: generated file + includes, never a rewrite of the user's file ---

def test_init_writes_the_persona_and_both_includes(fresh):
    assert (fresh / ".tsubasa" / PERSONA_FILE).is_file()
    text = (fresh / "CLAUDE.md").read_text()
    assert f"@.tsubasa/{PERSONA_FILE}" in text
    assert "@.tsubasa/memory/hot.md" in text


def test_persona_is_marked_generated(fresh):
    # same convention as memory/hot.md, so `upgrade` may rewrite it freely
    assert "generated by tsubasa; do not edit" in (fresh / ".tsubasa" / PERSONA_FILE).read_text()


def test_existing_captain_gains_the_rules_and_keeps_its_own_claude_md(tmp_path):
    """The case the old guard broke: include already present, so nothing landed."""
    base = tmp_path / ".tsubasa"
    (base / "memory").mkdir(parents=True)
    (base / "captain.toml").write_text('[captain]\nname = "testcap"\n')
    mine = ("# My workspace\n\nOur own house rules, hand-written.\n\n"
            "@.tsubasa/memory/hot.md\n\n## More of my notes\n")
    (tmp_path / "CLAUDE.md").write_text(mine)

    notes = scaffold.ensure_claude_md(tmp_path, "testcap")

    persona = (base / PERSONA_FILE).read_text()
    assert all(rule in persona for rule in RULES)        # the fix landed
    after = (tmp_path / "CLAUDE.md").read_text()
    assert after.startswith(mine.rstrip() + "\n")        # their bytes, untouched
    assert after[len(mine.rstrip()) + 1:].strip() == f"@.tsubasa/{PERSONA_FILE}"
    assert any(PERSONA_FILE in n for n in notes)


def test_regenerating_is_idempotent(fresh):
    claude_md, persona = fresh / "CLAUDE.md", fresh / ".tsubasa" / PERSONA_FILE
    before = (claude_md.read_text(), persona.read_text())

    assert scaffold.ensure_claude_md(fresh, "testcap") == []   # nothing to report
    assert (claude_md.read_text(), persona.read_text()) == before
    assert claude_md.read_text().count(f"@.tsubasa/{PERSONA_FILE}") == 1


def test_stale_inline_persona_is_reported_not_rewritten(tmp_path):
    # a pre-persona.md captain has the prose inline; it is their file to delete
    (tmp_path / ".tsubasa").mkdir()
    inline = f"# Captain old (tsubasa)\n\n{PRINCIPLES_MD}\n@.tsubasa/memory/hot.md\n"
    (tmp_path / "CLAUDE.md").write_text(inline)

    notes = scaffold.ensure_claude_md(tmp_path, "old")

    assert any("superseded" in n and "can be deleted" in n for n in notes)
    assert inline in (tmp_path / "CLAUDE.md").read_text()


# --- one source of truth: the hook must not restate what persona.md carries ---

@pytest.mark.parametrize("source", ["startup", "resume", "clear", "compact"])
def test_hook_points_at_the_persona_instead_of_copying_it(fresh, source):
    out = hook_out(fresh, source)
    assert f".tsubasa/{PERSONA_FILE}" in out
    assert "GRAPH-FIRST" in out                      # the one imperative it keeps
    assert "You are captain-testcap" in out
    for rule in RULES:
        assert rule not in out


def test_hook_does_not_restate_the_persona_prose(fresh):
    out = hook_out(fresh)
    for moved in ("Response contract", "MEMORY ROUTING", "co-author trailers",
                  "subagents implement"):
        assert moved not in out


# --- recall is the skill that answers these questions ---

@pytest.mark.parametrize("phrase", [
    "Never emit an id you did not read",
    "evt-<today>-",
    "Lead with the literal recorded value",
    "successor never becomes the headline",
    "Separate the record from what you know",
    "not recorded here, from general knowledge",
])
def test_recall_skill_is_aligned(phrase):
    assert phrase in RECALL.read_text()


def test_recall_reaches_for_the_timeline_on_history_questions():
    skill = RECALL.read_text()
    assert 'tsubasa query --timeline "<topic>"' in skill
    for question in ('"has this been tried?"', '"why is X like this?"',
                     '"what is the status of X?"'):
        assert question in skill
    assert "reverts" in skill and "supersedes" in skill
