"""Memory tier generation: hot.md (always in context), index.md (warm),
domains/*.md (warm, per-domain). Regenerated after every ingest — never
hand-edited. Content is chosen by temperature score under a dynamic token
budget (hot_max_context × context window); the lowest-scored overflow is
demoted to warm with a pointer line so nothing silently disappears.
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..config import CaptainConfig
from ..models import Entity, Event, Task
from ..storage import Store
from . import temperature as temp


def generate(store: Store, cfg: CaptainConfig, now: datetime | None = None) -> dict:
    now = now or datetime.now(timezone.utc)
    entities = store.load_entities()
    events = {e.id: e for e in store.load_events()}
    tasks = store.load_tasks()

    scored_entities = sorted(
        ((temp.score_entity(e, cfg, now), e) for e in entities.values()),
        key=lambda p: -p[0],
    )
    scored_tasks = sorted(
        ((temp.score_task(t, cfg, now), t) for t in tasks.values()),
        key=lambda p: -p[0],
    )

    hot_lines, demoted = _build_hot(cfg, scored_entities, scored_tasks, events)
    store.memory_dir.mkdir(parents=True, exist_ok=True)
    (store.memory_dir / "hot.md").write_text("\n".join(hot_lines) + "\n")

    index_lines = _build_index(cfg, scored_entities, demoted)
    (store.memory_dir / "index.md").write_text("\n".join(index_lines) + "\n")

    domain_counts = _build_domains(store, cfg, scored_entities, events)

    return {
        "hot_tokens": temp.estimate_tokens("\n".join(hot_lines)),
        "hot_budget": cfg.hot_budget_tokens,
        "entities": len(entities),
        "tasks": len(tasks),
        "demoted": len(demoted),
        "domains": domain_counts,
    }


def _build_hot(cfg, scored_entities, scored_tasks, events) -> tuple[list[str], list[Entity]]:
    budget = cfg.hot_budget_tokens
    lines = [
        f"# {cfg.name} — hot knowledge",
        f"<!-- generated by tsubasa; do not edit. role: {cfg.role} -->",
        "",
    ]
    used = temp.estimate_tokens("\n".join(lines))
    demoted: list[Entity] = []

    active = [(s, t) for s, t in scored_tasks if t.state not in ("done", "abandoned")]
    if active:
        lines.append("## Active tasks")
        for s, t in active:
            evidence = t.history[-1].evidence if t.history else ""
            row = f"- {t.id} [{t.state}] {t.title}" + (f" — adr: {t.adr}" if t.adr else "") \
                + (f" — prs: {','.join(t.prs)}" if t.prs else "") + (f" ({evidence})" if evidence else "")
            lines.append(row)
        lines.append("")
        used = temp.estimate_tokens("\n".join(lines))

    goals = [(s, e) for s, e in scored_entities if e.type == "goal" and e.status == "active"]
    if goals:
        lines.append("## Direction — open goals (weigh these in every plan/design)")
        for s, e in goals:
            lines.append(_entity_block(e, events))
        lines.append("")
        used = temp.estimate_tokens("\n".join(lines))

    lines.append("## Knowledge")
    for s, e in scored_entities:
        if e.type == "goal":
            continue  # goals live in the Direction section
        if temp.tier_of(s) != "hot":
            break
        block = _entity_block(e, events)
        cost = temp.estimate_tokens(block)
        if used + cost > budget:
            demoted.append(e)
            continue
        lines.append(block)
        used += cost
    if demoted:
        lines.append("")
        lines.append(f"(+{len(demoted)} hot items demoted to warm by budget — see memory/index.md)")
    return lines, demoted


def _entity_block(e: Entity, events: dict[str, Event]) -> str:
    out = [f"- **{e.id}** ({e.type}, impact={e.impact}): {e.description or e.name}"]
    if e.summary:
        out.append(f"  - {e.summary}")
    for fact in e.key_facts[:3]:
        out.append(f"  - {fact}")
    recent = [events[i] for i in e.source_events[-2:] if i in events]
    for ev in recent:
        out.append(f"  - cite: {ev.id} ({ev.ts[:10]}) {ev.title}")
    return "\n".join(out)


def _build_index(cfg, scored_entities, demoted) -> list[str]:
    demoted_ids = {e.id for e in demoted}
    lines = [
        f"# {cfg.name} — knowledge index",
        "<!-- one line per entity; ask the captain to dig into any of them -->",
        "",
    ]
    for s, e in scored_entities:
        tier = "warm" if e.id in demoted_ids else temp.tier_of(s)
        status = " ⊘superseded" if e.status == "superseded" else ""
        lines.append(f"- [{tier}] {e.id} ({e.type}){status} — {e.description or e.name}")
    return lines


def _build_domains(store: Store, cfg, scored_entities, events) -> dict[str, int]:
    domains_dir = store.memory_dir / "domains"
    domains_dir.mkdir(parents=True, exist_ok=True)
    by_domain: dict[str, list] = {}
    for s, e in scored_entities:
        for d in e.domains or ["general"]:
            by_domain.setdefault(d, []).append((s, e))
    counts = {}
    for domain, pairs in sorted(by_domain.items()):
        lines = [f"# domain: {domain}", ""]
        for s, e in pairs:
            lines.append(_entity_block(e, events))
        (domains_dir / f"{domain}.md").write_text("\n".join(lines) + "\n")
        counts[domain] = len(pairs)
    return counts
