"""Memory tier generation: hot.md (always in context), index.md (warm),
domains/*.md (warm, per-domain). Regenerated after every ingest — never
hand-edited.

hot.md is a *map*, not a cache: the repos, the knowledge corpora and where
they live, open goals, incidents, and how the repos relate.
Document bodies (docs, designs, changelogs, principles, ADRs) are indexed,
not carried — the captain reads them on demand from the glob hot already
gives it. An A/B run on a 4-repo corpus scored the same 8/8 on a 19-entity
map as on the 172-entity cache while spending 39% fewer input tokens, and
routed better: it answered from hot alone where the fat version went hunting
with Glob for a file whose glob it was already holding.

Warm (index.md, domains/*.md) still lists everything, so nothing is lost.
The token budget (hot_max_context × context window) still applies; overflow
is demoted with a pointer line.
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..config import CaptainConfig
from ..models import Entity, Event, Relation, slugify

from ..storage import Store
from . import temperature as temp
from ..atomicio import write_text_atomic

MAP_TYPES = {"service", "external", "incident"}  # plus corpus-* (type doc)
MAP_ENDPOINTS = ("svc-", "ext-")                 # what the Topology section wires
DROP_FACTS = {"extensions",                      # near-always ".md"
              "adapter"}                         # restated by the description's kind word
FACT_REPEAT_KEEP = 2                             # a repo carries one `released:` per tag
SAMPLES_KEEP = 3
SAMPLE_WIDTH = 60
INLINE_FACT_WIDTH = 72                           # short facts share one line
CITE_HOIST_MIN = 2                               # repeats become a legend entry


def generate(store: Store, cfg: CaptainConfig, now: datetime | None = None) -> dict:
    now = now or datetime.now(timezone.utc)
    entities = store.load_entities()
    events = {e.id: e for e in store.load_events()}
    relations = store.load_relations()

    scored_entities = sorted(
        ((temp.score_entity(e, cfg, now), e) for e in entities.values()),
        key=lambda p: -p[0],
    )

    hot_lines, demoted = _build_hot(cfg, scored_entities, events, relations)
    store.memory_dir.mkdir(parents=True, exist_ok=True)
    write_text_atomic(store.memory_dir / "hot.md", "\n".join(hot_lines) + "\n")

    index_lines = _build_index(cfg, scored_entities, demoted)
    write_text_atomic(store.memory_dir / "index.md", "\n".join(index_lines) + "\n")

    domain_counts = _build_domains(store, cfg, scored_entities, events)

    return {
        "hot_tokens": temp.estimate_tokens("\n".join(hot_lines)),
        "hot_budget": cfg.hot_budget_tokens,
        "entities": len(entities),
        "demoted": len(demoted),
        "domains": domain_counts,
    }


def _is_map_entity(e: Entity, distilled: set[str] = frozenset()) -> bool:
    """The map: repos, corpora and their locating facts, incidents. Incidents
    are unconditional — the only incident in the reference corpus is
    impact=medium and an impact filter would have dropped it.

    `service`/`external` type alone is NOT enough. `study` mints one per
    component and dependency it reads out of a commit message: on the reference
    corpus that was 390 of them, and keying on type alone put every one in hot,
    silently undoing the reshape. A service somebody declared is workspace
    knowledge; one inferred from a commit subject is a search result. So an
    entity known ONLY to distillation is warm, everything else stays.
    """
    if e.id.startswith("corpus-") or e.type == "incident":
        return True
    return e.type in MAP_TYPES and e.id not in distilled


def _build_hot(cfg, scored_entities, events, relations) -> tuple[list[str], list[Entity]]:
    budget = cfg.hot_budget_tokens
    lines = [
        f"# {cfg.name} — hot knowledge",
        f"<!-- generated by tsubasa; do not edit. role: {cfg.role} -->",
        "<!-- a map of where knowledge lives, not the knowledge itself;"
        " read the globs below on demand. full list: memory/index.md -->",
        "",
    ]
    demoted: list[Entity] = []

    goals = [e for s, e in scored_entities if e.type == "goal" and e.status == "active"]
    distilled = {e.id for s, e in scored_entities
                 if e.source_events and all(
                     (events[i].source == "study") for i in e.source_events if i in events)}
    map_ents = [e for s, e in scored_entities if _is_map_entity(e, distilled)]
    kept = {e.id for e in map_ents}
    # Every edge between mapped endpoints, curated or distilled. Distillation
    # adds vague near-duplicates (adds_support_for / backs_up on one pair), so
    # this is not free, but it is knowledge and accuracy outranks token count:
    # restricting to curated edges is untested against the benchmark.
    topo = [r for r in relations
            if r.source in kept and r.target in kept
            and r.source.startswith(MAP_ENDPOINTS) and r.target.startswith(MAP_ENDPOINTS)]
    tags, legend = _cite_legend(goals + map_ents, topo, events)
    if legend:
        lines.append("## Citations")
        lines += legend
        lines.append("")
    used = temp.estimate_tokens("\n".join(lines))

    if goals:
        lines.append("## Direction — open goals (weigh these in every plan/design)")
        for e in goals:
            lines.append(_map_block(e, events, tags))
        lines.append("")
        used = temp.estimate_tokens("\n".join(lines))

    lines.append("## Knowledge")
    for e in map_ents:
        block = _map_block(e, events, tags)
        cost = temp.estimate_tokens(block)
        if used + cost > budget:
            demoted.append(e)
            continue
        lines.append(block)
        used += cost

    if topo:
        head = ["", "## Topology"]
        rows = [_relation_row(r, events, tags) for r in sorted(topo, key=lambda r: r.key())]
        cost = temp.estimate_tokens("\n".join(head + rows))
        if used + cost <= budget:
            lines += head + rows
            used += cost
    if demoted:
        lines.append("")
        lines.append(f"(+{len(demoted)} map entries demoted to warm by budget — see memory/index.md)")
    return lines, demoted


def _cite_text(ev: Event) -> str:
    return f"{ev.id} ({ev.ts[:10]}) {ev.title}"


def _cites(e: Entity, events: dict[str, Event]) -> list[str]:
    return [_cite_text(events[i]) for i in e.source_events[-2:] if i in events]


def _cite_legend(ents: list[Entity], topo: list[Relation],
                 events: dict[str, Event]) -> tuple[dict[str, str], list[str]]:
    """One `evt-…-workspace-map` citation is byte-identical on every corpus
    entry. Hoist any citation used more than once into a legend and leave a
    tag behind."""
    counts: dict[str, int] = {}
    for e in ents:
        for c in _cites(e, events):
            counts[c] = counts.get(c, 0) + 1
    for r in topo:
        ev = events.get(r.provenance)
        if ev is not None:
            counts[_cite_text(ev)] = counts.get(_cite_text(ev), 0) + 1
    tags, legend = {}, []
    for c, n in counts.items():
        if n < CITE_HOIST_MIN:
            continue
        tag = f"[c{len(tags) + 1}]"
        tags[c] = tag
        legend.append(f"- {tag} {c}")
    return tags, legend


def _relation_row(r: Relation, events: dict[str, Event], tags: dict[str, str]) -> str:
    ev = events.get(r.provenance)
    cite = _cite_text(ev) if ev is not None else ""
    mark = tags.get(cite, "")
    return f"- **{r.source}** {r.predicate} **{r.target}**{mark}" + \
        (f"\n  - cite: {cite}" if cite and not mark else "")


def _map_block(e: Entity, events: dict[str, Event], tags: dict[str, str]) -> str:
    cites = _cites(e, events)
    marks = "".join(tags[c] for c in cites if c in tags)
    impact = ", impact=high" if e.impact == "high" else ""
    out = [f"- **{e.id}** ({e.type}{impact}){marks}: {e.description or e.name}"]
    if e.summary:
        out.append(f"  - {e.summary}")
    inline, own = [], []
    seen: dict[str, int] = {}
    for fact in e.key_facts:
        key = fact.split(":", 1)[0].strip().lower()
        if key in DROP_FACTS:
            continue
        seen[key] = seen.get(key, 0) + 1
        if seen[key] > FACT_REPEAT_KEEP:
            continue  # a repeated key is a list, and lists belong in warm
        if key == "samples":
            own.append(f"  - {_trim_samples(fact)}")
        elif len(fact) <= INLINE_FACT_WIDTH:
            inline.append(fact)
        else:
            own.append(f"  - {fact}")
    inline += [f"{k}: +{n - FACT_REPEAT_KEEP} more"
               for k, n in seen.items() if n > FACT_REPEAT_KEEP]
    if inline:
        out.append("  - " + " | ".join(inline))
    out += own
    out += [f"  - cite: {c}" for c in cites if c not in tags]
    return "\n".join(out)


def _trim_samples(fact: str) -> str:
    key, _, rest = fact.partition(":")
    items = [t.strip()[:SAMPLE_WIDTH] for t in rest.split(";") if t.strip()][:SAMPLES_KEEP]
    return f"{key}: " + "; ".join(items)


def _entity_block(e: Entity, events: dict[str, Event]) -> str:
    out = [f"- **{e.id}** ({e.type}, impact={e.impact}): {e.description or e.name}"]
    if e.summary:
        out.append(f"  - {e.summary}")
    for fact in e.key_facts[:3]:
        out.append(f"  - {fact}")
    recent = [events[i] for i in e.source_events[-2:] if i in events]
    for ev in recent:
        out.append(f"  - cite: {ev.id} ({ev.ts[:10]}) {ev.title}")
    return "\n".join(out)


def _build_index(cfg, scored_entities, demoted) -> list[str]:
    demoted_ids = {e.id for e in demoted}
    lines = [
        f"# {cfg.name} — knowledge index",
        "<!-- one line per entity; ask the captain to dig into any of them -->",
        "",
    ]
    for s, e in scored_entities:
        tier = "warm" if e.id in demoted_ids else temp.tier_of(s)
        status = " ⊘superseded" if e.status == "superseded" else ""
        lines.append(f"- [{tier}] {e.id} ({e.type}){status} — {e.description or e.name}")
    return lines


def _build_domains(store: Store, cfg, scored_entities, events) -> dict[str, int]:
    domains_dir = store.memory_dir / "domains"
    domains_dir.mkdir(parents=True, exist_ok=True)
    by_domain: dict[str, list] = {}
    for s, e in scored_entities:
        for raw in e.domains or ["general"]:
            # the label becomes a filename; labels replayed from an existing
            # log or minted by a model are not trusted to stay inside domains/
            d = slugify(raw) or "general"
            by_domain.setdefault(d, []).append((s, e))
    counts = {}
    for domain, pairs in sorted(by_domain.items()):
        lines = [f"# domain: {domain}", ""]
        for s, e in pairs:
            lines.append(_entity_block(e, events))
        write_text_atomic(domains_dir / f"{domain}.md", "\n".join(lines) + "\n")
        counts[domain] = len(pairs)
    return counts
