"""Stage 1 of source discovery: a deterministic candidate map, no LLM.

`scan()` walks the workspace and reports *candidates*: every plausible
knowledge directory with the evidence a reader needs to judge it, file
count, extensions seen, sample filenames, whether it has an index. It
also attaches a vocabulary best-guess (adapter/kind/bucket), which is a
guess, not a verdict.

Stage 2 (an LLM pass, not implemented here) consumes `scan()` output
verbatim, together with each repo's README, and returns the final source
list. `plan()` is the offline fallback: it turns the guesses into
[[sources]] entries so `init` still works with no model around.

Everything `scan()` returns is plain JSON-serializable data; `tsubasa
source detect --json` dumps it as-is.
"""

from __future__ import annotations

import os
from collections import Counter
from pathlib import Path

from .adapters import base

# adapter, kind, impact, bucket, directory names (lowercase, '_' folded to '-').
# First match wins, so specific vocabularies sit above general ones.
VOCAB = (
    ("adr", "", "", "knowledge",
     ("adr", "adrs", "decisions", "decision-records", "kep", "keps", "rfc", "rfcs",
      "oteps", "teps", "proposals", "enhancements", "designs", "design-docs")),
    ("incident", "", "", "postmortem",
     ("postmortem", "postmortems", "post-mortems", "incidents", "outages", "retrospectives")),
    ("doc", "principle", "high", "best practice",
     ("principles", "guidelines", "conventions", "best-practices", "standards",
      "contribute", "contributing")),
    ("doc", "changelog", "", "changes",
     ("changelog", "changelogs", "release-notes", "releases", "news")),
    ("doc", "design", "", "knowledge",
     ("docs", "doc", "documentation", "architecture", "design")),
)

SKIP_DIRS = {
    "node_modules", "venv", "target", "build", "dist", "vendor", "__pycache__",
    "site-packages", "testdata", "fixtures", "third_party", "thirdparty",
    "translations", "i18n", "locale", "locales", "l10n",
}
INDEX_FILES = {"readme.md", "readme", "index.md", "index.rst"}

# Banners generated documents put at the top of themselves. Matching one is
# enough to exclude the file offline: nothing hand-written says this.
GENERATED_MARKERS = (
    "auto-generated", "autogenerated", "automatically generated", "@generated",
    "do not edit", "code generated by", "this file is generated",
    "generated file", "generated by protoc", "generated documentation",
)
STRONG_MARKERS = ("do not edit", "@generated", "code generated by")
COMMENT_PREFIXES = ("<!--", "//", "#", "/*", "*", "--", ";", "%")
MARKER_LINES = 6        # a generated banner sits at the very top, or it isn't one
MARKER_LINE_MAX = 200   # ...and it is a banner, not a paragraph about generation
OUTLIER_MIN_LINES = 800  # a file this long is worth a second look...
OUTLIER_RATIO = 6        # ...if it also dwarfs its siblings
MAX_SUSPECT = 5          # suspects reported per source, so the prompt stays small

DEPTH = 3          # directory levels walked inside each repo
MIN_HERE = 3       # knowledge files directly in a dir before its name stops mattering
MIN_TREE = 8       # knowledge files below it, same
README_MIN = 5     # extensionless READMEs before glob="**/README" is worth it
MAX_SOURCES = 12   # per repo, so one giant monorepo can't drown the config
SAMPLES = 5


# ------------------------------------------------------------------ stage 1

def scan(root: Path, depth: int = DEPTH) -> list[dict]:
    """Candidate knowledge directories, with evidence. Read-only."""
    out: list[dict] = []
    for repo, base in _repos(root):
        stats = _stats(base)
        for rel in sorted(stats):
            if rel == "." or _depth(rel) > depth:
                continue
            cand = _candidate(repo, rel, stats[rel])
            if cand:
                out.append(cand)
    return out


def _candidate(repo: str, rel: str, s: dict) -> dict | None:
    if not s["tree"]:
        return None
    guess = classify(rel.rsplit("/", 1)[-1])
    reason = "vocab"
    if not guess:
        # a subtree of extensionless READMEs (postgres src/backend) is design
        # prose no .md-shaped probe ever sees
        if s["readmes"] >= README_MIN and s["readmes"] * 2 >= s["tree"]:
            guess, reason = ("doc", "design", "", "knowledge"), "readme"
        elif s["here"] >= MIN_HERE or s["tree"] >= MIN_TREE:
            guess, reason = ("", "", "", ""), "volume"  # evidence for stage 2, no verdict
        else:
            return None
    adapter, kind, impact, bucket = guess
    return {
        "repo": repo,
        "path": _join(repo, rel),
        "name": rel.rsplit("/", 1)[-1],
        "depth": _depth(rel),
        "files": s["tree"],
        "files_here": s["here"],
        "readmes": s["readmes"],
        "extensions": dict(s["exts"].most_common(6)),
        "samples": s["samples"],
        "has_index": s["has_index"],
        "adapter": adapter,
        "kind": kind,
        "impact": impact,
        "bucket": bucket,
        "reason": reason,
    }


def classify(name: str) -> tuple[str, str, str, str] | None:
    """Vocabulary match on a directory name. Case- and separator-insensitive."""
    key = name.lower().replace("_", "-")
    for adapter, kind, impact, bucket, names in VOCAB:
        if key in names:
            return adapter, kind, impact, bucket
    return None


# ------------------------------------------------------------------ walking

def _repos(root: Path) -> list[tuple[str, Path]]:
    """The captain root plus any immediate subdirectory that is its own repo."""
    return [(".", root)] + [(c.name, c) for c in _subdirs(root) if (c / ".git").exists()]


def _subdirs(d: Path) -> list[Path]:
    return sorted(p for p in d.iterdir()
                  if p.is_dir() and not p.name.startswith(".") and p.name.lower() not in SKIP_DIRS)


def _stats(base: Path) -> dict[str, dict]:
    """Per-directory knowledge-file stats for one repo, keyed by relative path.

    Counts roll up from the leaves, so a shallow directory knows how much
    lives below it even past the reporting depth.
    """
    nested = {c.name for c in _subdirs(base) if (c / ".git").exists()}  # own base, walked separately
    stats: dict[str, dict] = {}
    for dirpath, dirnames, filenames in os.walk(base):
        rel = Path(dirpath).relative_to(base).as_posix()
        dirnames[:] = sorted(d for d in dirnames if not d.startswith(".")
                             and d.lower() not in SKIP_DIRS
                             and not (rel == "." and d in nested))
        stats[rel] = {"dirs": list(dirnames), "files": sorted(filenames)}
    for rel in sorted(stats, key=_depth, reverse=True):
        _roll_up(stats, rel)
    return stats


def _roll_up(stats: dict[str, dict], rel: str) -> None:
    s = stats[rel]
    here = [f for f in s["files"] if _is_knowledge(f)]
    exts = Counter(_ext(f) for f in s["files"])
    tree = len(here)
    readmes = sum(1 for f in here if f == "README")
    samples = list(here[:SAMPLES])
    for d in s["dirs"]:
        child = stats[_join(rel, d)]
        tree += child["tree"]
        readmes += child["readmes"]
        exts.update(child["exts"])
        samples += [f"{d}/{x}" for x in child["samples"][:SAMPLES - len(samples)]]
    s.update(here=len(here), tree=tree, readmes=readmes, exts=exts,
             samples=samples[:SAMPLES],
             has_index=any(f.lower() in INDEX_FILES for f in s["files"]))


def _is_knowledge(name: str) -> bool:
    return name.endswith(".md") or name == "README"


def _ext(name: str) -> str:
    return Path(name).suffix or (name if name in ("README", "OWNERS") else "(none)")


def _depth(rel: str) -> int:
    return 0 if rel == "." else rel.count("/") + 1


def _join(rel: str, sub: str) -> str:
    return sub if rel == "." else f"{rel}/{sub}"


# ------------------------------------------------------------------ offline plan

def detect_sources(root: Path, depth: int = DEPTH,
                   cap: int | None = None) -> tuple[list[dict], list[dict]]:
    """Git repos plus the offline plan. Returns (sources, dropped-by-cap)."""
    sources, dropped = plan(scan(root, depth), root, cap)
    return git_sources(root) + sources, dropped


def git_sources(root: Path) -> list[dict]:
    # .git is a file, not a directory, in submodules and linked worktrees,
    # exactly how most multi-repo workspaces are laid out
    found = [{"adapter": "git", "path": "."}] if (root / ".git").exists() else []
    return found + [{"adapter": "git", "path": c.name}
                    for c in _subdirs(root) if (c / ".git").exists()]


def plan(candidates: list[dict], root: Path,
         cap: int | None = None) -> tuple[list[dict], list[dict]]:
    """Turn best-guess candidates into [[sources]] entries.

    Two rules do the work. A nested candidate that classifies differently
    from an ancestor wins its subtree, and the ancestor keeps only what the
    nested one did not (non-recursive glob, plus one entry per uncovered
    sibling subtree). A nested candidate that classifies the *same* way is
    dropped: its ancestor already ingests it.
    """
    guessed = [c for c in candidates if c["adapter"]]
    chosen: dict[str, dict] = {}
    for c in sorted(guessed, key=lambda c: (c["depth"], c["path"])):
        anc = _ancestor(chosen, c["path"])
        if anc and _sig(chosen[anc]) == _sig(c):
            continue
        chosen[c["path"]] = c
    sources: list[dict] = []
    for path, c in sorted(chosen.items()):
        if not _ancestor(chosen, path):
            _expand(root, path, c, chosen, sources)
    return _cap([s for s in sources if s["files"]], MAX_SOURCES if cap is None else cap)


def _sig(c: dict) -> tuple:
    return c["adapter"], c["kind"], c["impact"], _leaf(c)


def _leaf(c: dict) -> str:
    return "README" if c["reason"] == "readme" else "*.md"


def _ancestor(chosen: dict, path: str) -> str | None:
    """Deepest already-chosen directory that contains `path`."""
    hits = [p for p in chosen if path.startswith(p + "/")]
    return max(hits, key=len) if hits else None


def _expand(root: Path, path: str, c: dict, chosen: dict[str, dict], out: list[dict]) -> None:
    """Emit sources covering everything under `path` no nested source owns."""
    leaf = _leaf(c)
    if not any(p.startswith(path + "/") for p in chosen):
        out.append(_source(root, path, c, f"**/{leaf}"))
        return
    out.append(_source(root, path, c, leaf))  # this level only; children below
    for sub in _subdirs(root / path):
        rel = f"{path}/{sub.name}"
        if rel in chosen:                                        # classifies on its own
            _expand(root, rel, chosen[rel], chosen, out)
        elif any(p.startswith(rel + "/") for p in chosen):        # a descendant does
            _expand(root, rel, c, chosen, out)
        else:
            out.append(_source(root, rel, c, f"**/{leaf}"))


def _source(root: Path, path: str, c: dict, glob: str) -> dict:
    generated, suspect, files = inspect_files(root / path, glob)
    src = {"adapter": c["adapter"], "path": path, "glob": glob,
           "files": files - len(generated), "bucket": c["bucket"], "repo": c["repo"]}
    if generated:
        src["exclude"] = generated
    if suspect:
        # not excluded offline: "long" is evidence, not a verdict. The
        # classification pass decides, and a human sees it either way.
        src["suspect"] = suspect
    if c["kind"]:
        src["kind"] = c["kind"]
    if c["impact"]:
        src["impact"] = c["impact"]
    return src


def inspect_files(d: Path, glob: str) -> tuple[list[str], list[str], int]:
    """(banner-marked generated files, long outliers, total matched).

    Both lists are source-relative paths. Generated ones are safe to exclude
    offline; outliers are only evidence — a 3k-line hand-written reference is
    a real thing, and dropping it silently would be the worse failure.
    """
    if not d.is_dir():
        return [], [], 0
    paths = sorted(p for p in d.glob(base.ci_glob(glob)) if p.is_file())
    generated: list[str] = []
    lines: list[tuple[int, str]] = []
    for p in paths:
        try:
            text = p.read_text(errors="replace")
        except OSError:
            continue
        rel = p.relative_to(d).as_posix()
        if has_generated_banner(text):
            generated.append(rel)
        else:
            lines.append((text.count("\n") + 1, rel))
    return generated, _outliers(lines), len(paths)


def has_generated_banner(text: str) -> bool:
    """A banner is at the top of the file and short.

    `postgres/src/backend/nodes/README` is hand-written design prose that
    happens to say "automatically generated" about the code it describes, in
    its body. Excluding that would be exactly the destructive mistake this
    heuristic exists to avoid, so position and shape both have to match.
    """
    body = text.split("\n---", 1)[1] if text.startswith("---\n") else text
    head = [ln.strip() for ln in body.splitlines() if ln.strip()][:MARKER_LINES]
    for i, line in enumerate(head):
        low = line.lower()
        if len(line) > MARKER_LINE_MAX or not any(m in low for m in GENERATED_MARKERS):
            continue
        # a directive is unambiguous anywhere up top; a softer phrase has to be
        # in banner position (first line) or banner shape (a comment/heading)
        if any(m in low for m in STRONG_MARKERS) or i == 0 or line.startswith(COMMENT_PREFIXES):
            return True
    return False


def _outliers(lines: list[tuple[int, str]]) -> list[str]:
    if len(lines) < 3:
        return []
    counts = sorted(n for n, _ in lines)
    median = counts[len(counts) // 2] or 1
    hits = [(n, rel) for n, rel in lines
            if n >= OUTLIER_MIN_LINES and n >= OUTLIER_RATIO * median]
    return [f"{rel} ({n} lines vs median {median})"
            for n, rel in sorted(hits, reverse=True)[:MAX_SUSPECT]]


def _cap(sources: list[dict], cap: int) -> tuple[list[dict], list[dict]]:
    """Keep the `cap` biggest sources per repo. Dropped ones are returned, never hidden."""
    kept: list[dict] = []
    dropped: list[dict] = []
    by_repo: dict[str, list[dict]] = {}
    for s in sources:
        by_repo.setdefault(s["repo"], []).append(s)
    for repo in sorted(by_repo):
        ranked = sorted(by_repo[repo], key=lambda s: (-s["files"], s["path"]))
        kept += ranked[:cap]
        dropped += ranked[cap:]
    kept.sort(key=lambda s: s["path"])
    dropped.sort(key=lambda s: s["path"])
    return kept, dropped
